#name: CI
#env: # 设置环境变量
#  TZ: Asia/Shanghai # 时区
#on:
#  schedule:
#    - cron:  '30 23 1/1 * ?'
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    timeout-minutes: 3
#    steps:
#      - uses: actions/checkout@v3
#      - name: Set up JDK 1.8
#        uses: actions/setup-java@v3
#        with:
#          java-version: '18'
#          distribution: 'temurin'
#      - name: Build with Maven
#        run: mvn -B package --file pom.xml
#      - name: SendWxTemplateMsg
#        run: sudo java -jar ./target/wechatpush-0.0.1-SNAPSHOT.jar
